# compactdns
# A lightweight DNS server with easy customization
# https://github.com/ninjamar/compactdns
# Copyright (c) 2025 ninjamar

# This file is licensed under the MIT license

# Example configuration for compactdns

[logging]
loglevel = "INFO"
# path = "./data/stdout.log"

[all]
# fallback_ttl = 1000
ttl_min = 400
max_workers = 50


[servers.host]
host = "127.0.0.1"
port = 53

[servers.tls]
host = "127.0.0.1"
port = 853
ssl_key = "key.pem"
ssl_cert = "cert.pem"


[servers.debug_shell]
host = "127.0.0.1"
port = 2055

[resolver]
recursive = true
# TODO: No resolvers if we use recursive

# Uncomment these lines for upstream resolver
# list = [
#     "1.1.1.1",
#     "1.0.0.1",
# ]
# add_system = false

# Uncomment these lines for upstream resolver
# [daemons.fastest_resolver]
# use=true
# test_name="github.com"
# interval = 100

[storage]
# List of paths containing directories of zones
zone_dirs = [
    "./example-zones"
]

# Text file to preload records
# preload_path = "./examples/preload.txt"
# Path to cache dump
# cache_path = "./data/cache.pk.lzma"
# Path to zone dump
# zone_path = "./data/zone.pk.lzma"