[tool.setuptools]
packages = ["cdns"]

[project]
name = "compactdns"
version = "0.0.103"
requires-python = ">=3.11"
dependencies = [
    "publicsuffixlist",
]

[project.scripts]
cdns = "cdns.cli:cli"
