# Records file syntax
# All hostnames use fnmatch syntax
# TODO: Allow ip of host in future

# Rules
[[rules]]
ttl = 0
# All hosts in blocklist get $target_ip
target_ip = "127.0.0.2"
hosts = [
    "example.com",
]

[[rules]]
target_ip = "96.7.128.198" # IP address of example.com
hosts = [
    "*.example.com", # All subdomains of example.com go to $target_ip
    "test.example.edu"
]

# Key-value pairs of hostname to ip address 
[target-list]
"example.edu" = "74.125.200.139"